### ISSUE TITLE
Issue with otlp http request to Tempo from Server example

### ISSUE THREAD

**Issue by chemadh** [marcingrzejszczak/observability-boot-blog-post#9]
Hello,

I'm trying to run the example using local Prometheus, Tempo, Loki and Grafana instances. Everything seems to be working OK except the tracing report from server example to Tempo (from client side it looks fine). Please find the logs showed by my server example (named observability-server in my case):

```
2024-11-25T22:37:18.117Z  WARN 259232 --- [observability-server] [318/v1/traces}}] [                                                 ] z.r.i.AsyncReporter$BoundedAsyncReporter : Spans were dropped due to exceptions. All subsequent errors will be logged at FINE level.
2024-11-25T22:37:18.118Z  WARN 259232 --- [observability-server] [318/v1/traces}}] [                                                 ] z.r.i.AsyncReporter$BoundedAsyncReporter : Dropped 4 spans due to BadRequest(400 Bad Request: "????proto: illegal wireType 7")

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "????proto: illegal wireType 7"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:830)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:691)
        at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinRestTemplateSender.postSpans(ZipkinRestTemplateSender.java:50)
        at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.HttpSender.postSpans(HttpSender.java:69)
        at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.HttpSender.postSpans(HttpSender.java:41)
        at zipkin2.reporter.BaseHttpSender.send(BaseHttpSender.java:123)
        at zipkin2.reporter.internal.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:266)
        at zipkin2.reporter.internal.AsyncReporter$Flusher.run(AsyncReporter.java:352)
        at java.base/java.lang.Thread.run(Thread.java:840)
```
I've checked up-to-date Prometheus, Tempo and Loki versions, daemon execution parameters and configurations to align with the ones  available in docker compose config and docker service config files posted, with no luck. Tempo service is not logging any error, but I can see in network captures that effectively the http connection from server example to Tempo is answered with this 400 response.

I hope that this problem could ring a bell to you, pointing me in the right direction to have the problem solved.

Kind Regards,
Chema

**Comment by marcingrzejszczak** [comment]
It doesn't ring a bell at all. Any ideas @making?

**Comment by making** [comment]
@chemadh Are you using brave-otel?

**Comment by chemadh** [comment]
Hello,

in both Client and Server esamples I'm using _micrometer-tracing-bridge-brave_ in combination of _io.zipkin.contrib.otel_. Client example communicates well with Tempo, but Server example throws the issue posted above. Please find below my server example's pom.xml file:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>net.javaguides</groupId>
	<artifactId>observability-server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>observability-server</name>
	<description>Observability demo - server service example</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-otlp</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-brave</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.contrib.otel</groupId>
			<artifactId>encoder-brave</artifactId>
			<version>0.1.0</version>
		</dependency>
		<dependency>
    		<groupId>com.github.loki4j</groupId>
    		<artifactId>loki-logback-appender</artifactId>
    		<version>1.5.2</version>
    		<scope>runtime</scope>
		</dependency>	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<!--<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>-->
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>${start.class}</mainClass>
					<layout>ZIP</layout>
					<layers>
						<enabled>false</enabled>
					</layers>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by making** [comment]
And did you configure
https://github.com/marcingrzejszczak/observability-boot-blog-post/blob/main/client/src/main/java/com/example/client/brave/BraveOtlpConfig.java
and
https://github.com/marcingrzejszczak/observability-boot-blog-post/blob/main/client/src/main/resources/application.properties#L12
?

Sharing all code will help.

**Comment by chemadh** [comment]
Thanks a lot for your support. AFAIK I have reproduced all the code of the original example (or at least I tried :). I've uploaded it in https://github.com/chemadh/springboot_observability for your referrence. Please let me know if you identify something wrong or missing.

**Comment by making** [comment]
@chemadh for the server side, move `BraveOtlpConfig` under `net.javaguides.observability_server` pacakge as `brave` package is not included in the component scan.

**Comment by chemadh** [comment]
Tested applyting this change and effectively now it works! Thanks a lot for your support and extraordinary fast response, and of course, congratulations for this very valuable example. 

Just a comment: it seems that the documentation associated to this example in https://spring.io/blog/2022/10/12/observability-with-spring-boot-3 is not alligned with the current example code evolution (or maybe I'm missing a blog entry that updates that one).
